# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 개발자 팟캐스트 stdout.fm
description: >- # this means to ignore newlines until "baseurl:"
  클라우드, 개발, 가젯에 대해 이야기하는 프로그래머 팟캐스트 #stdoutfm
url: "https://stdout.fm" # the base hostname & protocol for your site, e.g. http://example.com
keywords: ["podcast", "software", "ruby", "tech", "technology", "seapy", "nacyot", "racoony", "apple", "aws", "cloud", "infra", "팟캐스트", "소프트웨어", "개발", "개발자", "클라우드", "루비", "테크"]

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

owner:
  name: stdout.fm
  email: stdout.fm@gmail.com
  avatar: logo.png
  bio: "클라우드, 개발, 가젯에 대해 이야기하는 프로그래머 팟캐스트 #stdoutfm"
  podbbang: http://www.podbbang.com/ch/1768796
  podty: https://www.podty.me/cast/188843
  youtube: https://www.youtube.com/channel/UCni26Y9C0Z7H36hPPHuqpSg
  itunes: https://itunes.apple.com/au/podcast/stdout-fm/id1440414478
  facebook: https://www.facebook.com/stdout.fm
  twitter: https://twitter.com/stdoutfm
  patreon: https://www.patreon.com/stdoutfm
